cmake_minimum_required(VERSION 3.8)
project(abb_irb1200_gripper_control)
if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
  add_compile_options(-Wall -Wextra -Wpedantic)
endif()
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(rclcpp_action REQUIRED)
find_package(moveit_ros_planning_interface REQUIRED)
find_package(geometry_msgs REQUIRED)
find_package(trajectory_msgs REQUIRED)
find_package(control_msgs REQUIRED)
add_executable(pick_place_demo src/pick_place_demo.cpp)
ament_target_dependencies(pick_place_demo rclcpp rclcpp_action moveit_ros_planning_interface geometry_msgs trajectory_msgs control_msgs)
install(TARGETS pick_place_demo DESTINATION lib/${PROJECT_NAME})
install(DIRECTORY launch config DESTINATION share/${PROJECT_NAME})
ament_package()
